window.onload=function(){$('body').addClass('loaded');$(".white").hide();$(".game1").click(function(){$(".white").hide();$(".typus").show()});$(".game2").click(function(){$(".white").hide();$(".snake").show()});$(".game3").click(function(){$(".white").hide();$(".matching").show()});var canv=document.getElementById("gc");var ctx=canv.getContext("2d");var textt=document.getElementById("scorey");var finalscore=document.getElementById("finalscore");var moreinfo=document.getElementById("moreinfo");var filter=document.getElementById("filter");var mainn=document.getElementById("container");document.addEventListener("keydown",keyPush);setInterval(game,1000/10);var playerY=10;var playerX=10;var gridsize=20;var tilecount=20;var appleX=15;var appleY=15;var velocityX=0;var velocityY=0;var trail=[];var tail=5;var score=0;var start=!0;function game(){playerX+=velocityX;playerY+=velocityY;if(playerX<0){playerX=tilecount-1}
    if(playerX>tilecount-1){playerX=0}
    if(playerY<0){playerY=tilecount-1}
    if(playerY>tilecount-1){playerY=0}
    ctx.fillStyle="#7AA252";ctx.fillRect(0,0,canv.width,canv.height);ctx.fillStyle="#1E1E1E";for(i=0;i<trail.length;i++){ctx.fillRect(trail[i].x*gridsize,trail[i].y*gridsize,gridsize-2,gridsize-2);if(trail[i].x==playerX&&trail[i].y==playerY){tail=5;score=0;textt.innerHTML="Score : "+0;if(!start){moreinfo.style.display="block";filter.style.display="block";break}}else{start=!1}}
    trail.push({x:playerX,y:playerY});while(trail.length>tail){trail.shift()}
    if(appleX==playerX&&appleY==playerY){tail++;appleX=Math.floor(Math.random()*tilecount);appleY=Math.floor(Math.random()*tilecount);a=++score;textt.innerHTML="Score: "+a.toString(10);finalscore.innerHTML="Final score: "+a.toString(10)}
    ctx.fillStyle="#1E1E1E";ctx.fillRect(appleX*gridsize,appleY*gridsize,gridsize/2.5,gridsize/2.5);ctx.fillRect(appleX*gridsize+gridsize/2,appleY*gridsize,gridsize/2.5,gridsize/2.5);ctx.fillRect(appleX*gridsize+gridsize/2,appleY*gridsize+gridsize/2,gridsize/2.5,gridsize/2.5);ctx.fillRect(appleX*gridsize,appleY*gridsize+gridsize/2,gridsize/2.5,gridsize/2.5)}
    function keyPush(evt){switch(evt.keyCode){case 37:velocityX=-1;velocityY=0;break;case 38:velocityX=0;velocityY=-1;break;case 39:velocityX=1;velocityY=0;break;case 40:velocityX=0;velocityY=1;break}}}
$('#again').click(function(){location.reload()})